// The lifecycle harness replaces this file only in its private temporary copy.
// Keeping the repository copy invalid prevents accidental non-test execution.
export type UpdaterLifecycleControl = {
	readonly runToken: string;
	readonly identifier: string;
	readonly initialVersion: string;
	readonly targetVersion: string;
	readonly channel: string;
	readonly channelRoot: string;
	readonly appBundlePath: string;
	readonly browserProfileRoot: string;
	readonly signalDirectory: string;
	readonly eventLogPath: string;
	readonly failurePath: string;
	readonly relaunchSentinelPath: string;
	readonly updateActivationPath: string;
	readonly bootstrapVerificationPath: string;
};

export const control: UpdaterLifecycleControl = (() => {
	throw new Error("updater lifecycle control was not generated by the harness");
})();
