// @dash cli=0.1.0 cottontail=0.1.1-canary.2
export default {
	scripts: {
		start: "dash src/sdks/bun/index.ts",
		"check-zig-version": "vendors/zig/zig version",
		"check-rust-version": "vendors/rust/bin/rustc --version",
		"build:dev": "dash build.ts",
		"build:local": "scripts/build-local.js",
		"build:release": "dash build.ts --release",
		dev: "scripts/dev.ts",
		"dev:test": "scripts/dev.test.ts",
		"dev:clean": "cd ../kitchen && rm -rf node_modules vendors/cef && cd ../package && dash dev",
		"dev:canary": "dash install && dash build:release && cd ../kitchen && dash install && dash electrobun build --env=canary",
		"dev:stable": "dash install && dash build:release && cd ../kitchen && dash install && dash electrobun build --env=stable",
		"build:docs:release": "cd ../docs && npm run build",
		"npm:publish": "dash build:release && npm publish",
		"npm:publish:beta": "dash build:release && npm publish --tag beta",
		typecheck: "./node_modules/.bin/tsc --noEmit && cd ../kitchen && ./node_modules/.bin/tsc --noEmit",
		"push:beta": "dash typecheck && node scripts/push-version.js beta",
		"push:patch": "dash typecheck && node scripts/push-version.js patch",
		"push:minor": "dash typecheck && node scripts/push-version.js minor",
		"push:major": "dash typecheck && node scripts/push-version.js major",
		"push:stable": "dash typecheck && node scripts/push-version.js stable",
		"build:push:artifacts": "node scripts/build-and-upload-artifacts.js",
		"test:unit": "dash test src/shared src/sdks/bun src/config",
		"bump-cef": "dash scripts/update-cef-version.ts",
	},
};
