export default {
	scripts: {
		start: "./vendors/cottontail/cottontail src/sdks/bun/index.ts",
		"check-zig-version": "vendors/zig/zig version",
		"check-rust-version": "vendors/rust/bin/rustc --version",
		"build:dev": "./vendors/dash-cli/dash build.ts",
		"build:local": "scripts/build-local.js",
		"build:release": "./vendors/dash-cli/dash build.ts --release",
		dev: "scripts/dev.ts",
		"dev:test": "scripts/dev.test.ts",
		"dev:clean": "cd ../kitchen && rm -rf node_modules vendors/cef && cd ../package && ./vendors/dash-cli/dash dev",
		"dev:canary": "npm install && ./vendors/dash-cli/dash build:release && cd ../kitchen && npm install && ../package/bin/dash electrobun build --env=canary",
		"dev:stable": "npm install && ./vendors/dash-cli/dash build:release && cd ../kitchen && npm install && ../package/bin/dash electrobun build --env=stable",
		"build:docs:release": "cd ../docs && npm run build",
		"npm:publish": "./vendors/dash-cli/dash build:release && npm publish",
		"npm:publish:beta": "./vendors/dash-cli/dash build:release && npm publish --tag beta",
		typecheck: "./node_modules/.bin/tsc --noEmit && cd ../kitchen && ./node_modules/.bin/tsc --noEmit",
		"push:beta": "./vendors/dash-cli/dash typecheck && node scripts/push-version.js beta",
		"push:patch": "./vendors/dash-cli/dash typecheck && node scripts/push-version.js patch",
		"push:minor": "./vendors/dash-cli/dash typecheck && node scripts/push-version.js minor",
		"push:major": "./vendors/dash-cli/dash typecheck && node scripts/push-version.js major",
		"push:stable": "./vendors/dash-cli/dash typecheck && node scripts/push-version.js stable",
		"build:push:artifacts": "node scripts/build-and-upload-artifacts.js",
		"test:unit": "./vendors/cottontail/cottontail test src/shared src/sdks/bun src/config",
		"bump-cef": "./vendors/dash-cli/dash scripts/update-cef-version.ts",
	},
};
