// @dash cli=0.2.0-canary.2 cottontail=0.1.1-canary.2
export default {
	scripts: {
		start: "hutch src/sdks/bun/index.ts",
		"check-zig-version": "vendors/zig/zig version",
		"check-rust-version": "vendors/rust/bin/rustc --version",
		"build:dev": "hutch build.ts",
		"build:local": "scripts/build-local.js",
		"build:release": "hutch build.ts --release",
		dev: "scripts/dev.ts",
		"dev:test": "scripts/dev.test.ts",
		"dev:clean": "cd ../kitchen && rm -rf node_modules vendors/cef && cd ../package && hutch dev",
		"dev:canary": "hutch install && hutch build:release && cd ../kitchen && hutch install && hutch electrobun build --env=canary",
		"dev:production": "hutch install && hutch build:release && cd ../kitchen && hutch install && hutch electrobun build --env=production",
		"build:docs:release": "cd ../docs && hutch run build",
		"npm:publish": "hutch build:release && npm publish",
		"npm:publish:beta": "hutch build:release && npm publish --tag beta",
		typecheck: "./node_modules/.bin/tsc --noEmit && cd ../kitchen && ./node_modules/.bin/tsc --noEmit",
		"push:beta": "hutch typecheck && node scripts/push-version.js beta",
		"push:patch": "hutch typecheck && node scripts/push-version.js patch",
		"push:minor": "hutch typecheck && node scripts/push-version.js minor",
		"push:major": "hutch typecheck && node scripts/push-version.js major",
		"push:stable": "hutch typecheck && node scripts/push-version.js stable",
		"build:push:artifacts": "node scripts/build-and-upload-artifacts.js",
		"test:unit": "hutch test src/shared src/sdks/bun src/config",
		"bump-cef": "hutch scripts/update-cef-version.ts",
	},
};
